# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(
        regex="^user/~create/$",
        view=views.userCreateView.as_view(),
        name='user_create',
    ),
    url(
        regex="^user/(?P<pk>\d+)/~delete/$",
        view=views.userDeleteView.as_view(),
        name='user_delete',
    ),
    url(
        regex="^user/(?P<pk>\d+)/$",
        view=views.userDetailView.as_view(),
        name='user_detail',
    ),
    url(
        regex="^user/(?P<pk>\d+)/~update/$",
        view=views.userUpdateView.as_view(),
        name='user_update',
    ),
    url(
        regex="^user/$",
        view=views.userListView.as_view(),
        name='user_list',
    ),
	url(
        regex="^organisation/~create/$",
        view=views.organisationCreateView.as_view(),
        name='organisation_create',
    ),
    url(
        regex="^organisation/(?P<pk>\d+)/~delete/$",
        view=views.organisationDeleteView.as_view(),
        name='organisation_delete',
    ),
    url(
        regex="^organisation/(?P<pk>\d+)/$",
        view=views.organisationDetailView.as_view(),
        name='organisation_detail',
    ),
    url(
        regex="^organisation/(?P<pk>\d+)/~update/$",
        view=views.organisationUpdateView.as_view(),
        name='organisation_update',
    ),
    url(
        regex="^organisation/$",
        view=views.organisationListView.as_view(),
        name='organisation_list',
    ),
	url(
        regex="^roles/~create/$",
        view=views.rolesCreateView.as_view(),
        name='roles_create',
    ),
    url(
        regex="^roles/(?P<pk>\d+)/~delete/$",
        view=views.rolesDeleteView.as_view(),
        name='roles_delete',
    ),
    url(
        regex="^roles/(?P<pk>\d+)/$",
        view=views.rolesDetailView.as_view(),
        name='roles_detail',
    ),
    url(
        regex="^roles/(?P<pk>\d+)/~update/$",
        view=views.rolesUpdateView.as_view(),
        name='roles_update',
    ),
    url(
        regex="^roles/$",
        view=views.rolesListView.as_view(),
        name='roles_list',
    ),
	url(
        regex="^permissions/~create/$",
        view=views.permissionsCreateView.as_view(),
        name='permissions_create',
    ),
    url(
        regex="^permissions/(?P<pk>\d+)/~delete/$",
        view=views.permissionsDeleteView.as_view(),
        name='permissions_delete',
    ),
    url(
        regex="^permissions/(?P<pk>\d+)/$",
        view=views.permissionsDetailView.as_view(),
        name='permissions_detail',
    ),
    url(
        regex="^permissions/(?P<pk>\d+)/~update/$",
        view=views.permissionsUpdateView.as_view(),
        name='permissions_update',
    ),
    url(
        regex="^permissions/$",
        view=views.permissionsListView.as_view(),
        name='permissions_list',
    ),
	]
